# Generated by ros2-analysis from the ROS 2 interface definitions example_interfaces/msg: do not edit.


class Bool:

    def __init__(self, *, data=False):
        self.data = data


class Byte:

    def __init__(self, *, data=0):
        self.data = data


class ByteMultiArray:

    def __init__(self, *, layout=None, data=None):
        if layout is None:
            layout = MultiArrayLayout()
        self.layout = layout
        if data is None:
            data = []
        self.data = data


class Char:

    def __init__(self, *, data=0):
        self.data = data


class Empty:

    def __init__(self):
        pass


class Float32:

    def __init__(self, *, data=0.0):
        self.data = data


class Float32MultiArray:

    def __init__(self, *, layout=None, data=None):
        if layout is None:
            layout = MultiArrayLayout()
        self.layout = layout
        if data is None:
            data = []
        self.data = data


class Float64:

    def __init__(self, *, data=0.0):
        self.data = data


class Float64MultiArray:

    def __init__(self, *, layout=None, data=None):
        if layout is None:
            layout = MultiArrayLayout()
        self.layout = layout
        if data is None:
            data = []
        self.data = data


class Int16:

    def __init__(self, *, data=0):
        self.data = data


class Int16MultiArray:

    def __init__(self, *, layout=None, data=None):
        if layout is None:
            layout = MultiArrayLayout()
        self.layout = layout
        if data is None:
            data = []
        self.data = data


class Int32:

    def __init__(self, *, data=0):
        self.data = data


class Int32MultiArray:

    def __init__(self, *, layout=None, data=None):
        if layout is None:
            layout = MultiArrayLayout()
        self.layout = layout
        if data is None:
            data = []
        self.data = data


class Int64:

    def __init__(self, *, data=0):
        self.data = data


class Int64MultiArray:

    def __init__(self, *, layout=None, data=None):
        if layout is None:
            layout = MultiArrayLayout()
        self.layout = layout
        if data is None:
            data = []
        self.data = data


class Int8:

    def __init__(self, *, data=0):
        self.data = data


class Int8MultiArray:

    def __init__(self, *, layout=None, data=None):
        if layout is None:
            layout = MultiArrayLayout()
        self.layout = layout
        if data is None:
            data = []
        self.data = data


class MultiArrayDimension:

    def __init__(self, *, label='', size=0, stride=0):
        self.label = label
        self.size = size
        self.stride = stride


class MultiArrayLayout:

    def __init__(self, *, dim=None, data_offset=0):
        if dim is None:
            dim = []
        self.dim = dim
        self.data_offset = data_offset


class String:

    def __init__(self, *, data=''):
        self.data = data


class UInt16:

    def __init__(self, *, data=0):
        self.data = data


class UInt16MultiArray:

    def __init__(self, *, layout=None, data=None):
        if layout is None:
            layout = MultiArrayLayout()
        self.layout = layout
        if data is None:
            data = []
        self.data = data


class UInt32:

    def __init__(self, *, data=0):
        self.data = data


class UInt32MultiArray:

    def __init__(self, *, layout=None, data=None):
        if layout is None:
            layout = MultiArrayLayout()
        self.layout = layout
        if data is None:
            data = []
        self.data = data


class UInt64:

    def __init__(self, *, data=0):
        self.data = data


class UInt64MultiArray:

    def __init__(self, *, layout=None, data=None):
        if layout is None:
            layout = MultiArrayLayout()
        self.layout = layout
        if data is None:
            data = []
        self.data = data


class UInt8:

    def __init__(self, *, data=0):
        self.data = data


class UInt8MultiArray:

    def __init__(self, *, layout=None, data=None):
        if layout is None:
            layout = MultiArrayLayout()
        self.layout = layout
        if data is None:
            data = []
        self.data = data


class WString:

    def __init__(self, *, data=''):
        self.data = data
