# Generated by ros2-analysis from the ROS 2 interface definitions builtin_interfaces/msg: do not edit.


class Duration:

    def __init__(self, *, sec=0, nanosec=0):
        self.sec = sec
        self.nanosec = nanosec


class Time:

    def __init__(self, *, sec=0, nanosec=0):
        self.sec = sec
        self.nanosec = nanosec
