# Generated by ros2-analysis from the ROS 2 interface definitions example_interfaces/action: do not edit.


class Fibonacci_Goal:

    def __init__(self, *, order=0):
        self.order = order


class Fibonacci_Result:

    def __init__(self, *, sequence=None):
        if sequence is None:
            sequence = []
        self.sequence = sequence


class Fibonacci_Feedback:

    def __init__(self, *, sequence=None):
        if sequence is None:
            sequence = []
        self.sequence = sequence


class Fibonacci:
    Goal = Fibonacci_Goal
    Result = Fibonacci_Result
    Feedback = Fibonacci_Feedback
