# Generated by ros2-analysis from the ROS 2 interface definitions example_interfaces/srv: do not edit.


class AddTwoInts_Request:

    def __init__(self, *, a=0, b=0):
        self.a = a
        self.b = b


class AddTwoInts_Response:

    def __init__(self, *, sum=0):
        self.sum = sum


class AddTwoInts:
    Request = AddTwoInts_Request
    Response = AddTwoInts_Response


class SetBool_Request:

    def __init__(self, *, data=False):
        self.data = data


class SetBool_Response:

    def __init__(self, *, success=False, message=''):
        self.success = success
        self.message = message


class SetBool:
    Request = SetBool_Request
    Response = SetBool_Response


class Trigger_Request:

    def __init__(self):
        pass


class Trigger_Response:

    def __init__(self, *, success=False, message=''):
        self.success = success
        self.message = message


class Trigger:
    Request = Trigger_Request
    Response = Trigger_Response
